### PR TITLE
Feat/banner

### PR DESCRIPTION
**Pull request by davidseid**
@tremarkley - Hey Harry, paired with you for code review this sprint, so if you get a few minutes please take a look. However, if you don't get to it today I can always ping Erin for tomorrow's sprint to have her look at this, so no worries either way.

This pr is for the basic rendering of a stateful banner component and "view photos" button, along with my first foray into jest/enzyme tests and the beginnings of using bootstrap. My tests are passing but they are very basic since I haven't yet figured out function mocking or how best to test things like click handlers when they depend on a click from a child component, etc.

### CODE REVIEW

**Comment by davidseid** [comment]
[S - Write ViewPhotoButtonHandler on PhotoGallery Component and connect it to the View Photos Button](https://trello.com/c/p30D06fq/57-s-write-viewphotobuttonhandler-on-photogallery-component-and-connect-it-to-the-view-photos-button)

**Comment by davidseid** [comment]
[S - Create View Photos Button](https://trello.com/c/kXw9ghcL/49-s-create-view-photos-button)

**Comment by davidseid** [comment]
[S - Write Test that Button Exists](https://trello.com/c/aHtkrmUv/52-s-write-test-that-button-exists)

**Comment by davidseid** [comment]
[S - Pass in Pair Photos](https://trello.com/c/YtQfqZ6k/48-s-pass-in-pair-photos)

**Comment by davidseid** [comment]
[S - Write Test for Photos Display](https://trello.com/c/mQSamrjJ/51-s-write-test-for-photos-display)

**Comment by davidseid** [comment]
[M - Create Unit Test for Banner](https://trello.com/c/9Z7f4YaB/54-m-create-unit-test-for-banner)

**Comment by davidseid** [comment]
[M - Write First Tests that Main module renders and pulls data](https://trello.com/c/jIt6MyCP/42-m-write-first-tests-that-main-module-renders-and-pulls-data)

**Comment by davidseid** [comment]
[M - PhotoGallery Component should get ID photos to State on Mount](https://trello.com/c/VDC3CIVV/39-m-photogallery-component-should-get-id-photos-to-state-on-mount)

**Review by tremarkley — CHANGES_REQUESTED** [review]
This all looks good! Nice job on getting jest and enzyme setup and working. 

A couple minor things you might want to consider:
- The naming of PhotoGallery.js was a bit confusing to me. When galleryView is true will it be rendering a different component? To me it seems to make sense that photoGallery would be what is rendered when galleryView is true. The only reason I say that, is because they both have gallery in their name.
- Inside the dependencies of your package.json I noticed that you have several testing dependencies in there, like puppeteer, jest, enzyme, etc. I believe that testing frameworks should be placed in the devDependencies section of your package.json since they are only required for development.

Overall, great job, these were just some very small things I noticed.

**Comment by davidseid** [comment]
@tremarkley - Thanks so much for your feedback, Harry. I totally agree on the PhotoGallery naming and I've generalized that component to just be called Photos so it will have a Banner component and a Gallery component that conditionally renders, that should hopefully clarify. 

I checked my package.json and it looked to me like my jest, enzyme, and puppeteer were in fact in my devdependencies not my regular dependencies. Do you mind double checking that real quick? Wondering if I'm somehow looking at the wrong package.json or something...

Thanks!

**Comment by tremarkley** [comment]
Hey @davidseid I'm really sorry about the package.json, you're right about the devDependencies. When looking at the changes in github it seems to cut out certain parts of the file, which made it look like everything was under dependencies. (see attachment)
screen shot 2018-02-28 at 10 02 17 am

**Comment by davidseid** [comment]
@tremarkley -- no worries at all, just double checking. Thanks, Harry.

**Pull request merged**
