### PR TITLE
Update ReadME -- ready for first pull request

### PR DESCRIPTION
**Pull request by davidseid**
@tremarkley -- I'm paired with Annisa for this sprint, but since she is already looking at one for you, would you mind looking at this when you get a sec? Since I didn't initially create a separate branch for this request I already pushed to master and this is only covering a small change in the README, but if you could look through my repo generally for any suggestions that would be great.

First pull request: 
- Webpack configuration
- Express server setup
- MongoDB - mongoose setup
- Seed database file and package.json script written

Question: I'm not certain if I should be closing my database connection somewhere in my code, and if so, where that should be, if you have any advice about that please let me know.

### CODE REVIEW

**Comment by davidseid** [comment]
[M - Set up Express Server](https://trello.com/c/GWH5xyjy/23-m-set-up-express-server)

**Comment by davidseid** [comment]
[L - Seed Database](https://trello.com/c/jSXzWnEE/25-l-seed-database)

**Comment by davidseid** [comment]
[S - Refactor seed-database work to occur in separate file and import into index.js](https://trello.com/c/okulbCk7/28-s-refactor-seed-database-work-to-occur-in-separate-file-and-import-into-indexjs)

**Comment by davidseid** [comment]
[M - Set up Mongo + Mongoose DB](https://trello.com/c/7tIgS6sL/24-m-set-up-mongo-mongoose-db)

**Comment by davidseid** [comment]
[M - Build out package.json / Install dependencies](https://trello.com/c/P35hflOm/22-m-build-out-packagejson-install-dependencies)

**Comment by davidseid** [comment]
[Generate Example Data - M](https://trello.com/c/y1vFmx7R/12-generate-example-data-m)

**Comment by davidseid** [comment]
[Make initial pull request with dev setup, database, and server](https://trello.com/c/PYMpn6WA/30-make-initial-pull-request-with-dev-setup-database-and-server)

**Comment by tremarkley** [comment]
I noticed that in your package.json your start script has the following:

`"start": "webpack-dev-server --progress --colors --config ./webpack.config.js"`

You might want to consider renaming this script to `“dev”`, `“start”` is normally reserved for commands that should be run upon deploying your project to another server. I haven’t used webpack-dev-server before, so take this with a grain of salt but I believe it is used for when you’re writing code and want it to automatically recompile any changes in your code to bundle.js.

Based on my limited experience I think the best practice is to put webpack commands inside the `“build”` script in package.json. If you use `“webpack -d —watch”` it will build your bundle.js in development mode and watch for changes. `“webpack -p”` builds it in production mode. I am still new to all this so I am not entirely sure on it but this is just my understanding/experience up to this point. Take a look at the scripts section of this package.json for a good example of using webpack in a package.json: https://github.com/tamizhvendan/blog-samples/blob/master/react-hello-world/package.json.

I am not sure what autoIndex does but it looks like you might be duplicating some work in your roomSchema (seed-db.js)

```
const roomSchema = new Schema({
	  roomId: Number,
	  photos: [{ photoId: Number, url: String, caption: String }],
	}, { autoIndex: false });


roomSchema.set('autoIndex', false);
```

Also if you are considering using this roomSchema throughout your application it might make sense to break it out into it’s own file and then import it into seed-db and where ever else you see fit.

Regarding disconnecting your db, I think it is best practice to disconnect from it after you are done seeding the db. In order to do that, you would have to set this up in a promise or callback to be called after all your documents have been created.

All that being said, most of this stuff is pretty nit picky. Overall, this all looks really good.

**Comment by davidseid** [comment]
@tremarkley -- your feedback was super helpful. thanks!

I adjusted my npm webpack scripts, got rid of extraneous autoIndex schema params, moved my roomSchema to a new file, and promisifed my database seeding so I could close the connection. Please take a quick look when you get a sec and let me know if you have any other recommended changes.

**Comment by tremarkley** [comment]
@davidseid looks awesome! great work

**Pull request merged**
