### PR TITLE
Feat/gallery

### PR DESCRIPTION
**Pull request by davidseid**
@EvaFro -- Hey Erin, got a pull request for you! Please take a look when you get a second. This is covering the rendering and basic functionality and styling of my main gallery component (which is the 'lightbox' modal component) as well as its child components: spotlight, thumbnail list, and thumbnails. Sorry it is kind of a big one, should have broken this down into smaller pull requests, but had a hard time doing that because all the child components depended on this one. Nothing is really changed on the server or db side though. Thanks!

--forgot to mention-- I attempted to include at least a few tests for each of the react components, though they are super basic right now since they represent just rendering, I still need to make them much more robust and include functionality testing.

### CODE REVIEW

**Comment by davidseid** [comment]
[As a user, display gallery view on view photos button click](https://trello.com/c/1Gsn36GM/9-as-a-user-display-gallery-view-on-view-photos-button-click)

**Comment by davidseid** [comment]
[As a user, see caption of displayed photo in gallery view](https://trello.com/c/p2o4X83T/10-as-a-user-see-caption-of-displayed-photo-in-gallery-view)

**Comment by EvaFro** [comment]
@davidseid This looks great. It was kind of hard to tell all the things that are going on.  Then the only comment that I had while looking through most of your changes was that you had a lot going on in the gallery component. You seemed to repeat yourself a lot when it came to changing the demo class and the number next class. I think by the end you broke these out into separate components. So I guess my  only comment is maybe if you realize you are going to be doing a lot of the same work, even if its a test separate, figure out ways to not repeat yourself. If you don't want to rush strait into a new component you can always do a for loop instead. That way you don't have to rewrite the same code every time you want to change something.

**Comment by davidseid** [comment]
@EvaFro -- Thanks for the feedback, Erin. Yeah apologies this pull request was confusing, the main reason is that I went through a lot of trial and error setting up my lightbox gallery. I actually copied a non-react tutorial at first (that is where I got the demo class, etc), and then once I saw that that fundamentally worked, I ended up refactoring it completely from scratch in a react component style so the demo class etc were entirely removed by the end. I think the trial and error was unfortunately something I just had to work through because I had never set up a lightbox gallery before, but sorry it made for such confusing changes. Appreciate the feedback on avoiding repetition and will try to keep my pull requests simpler going forward, this one was kind of a frankenstein. I'm going to merge this, but definitely let me know if there are any other specific suggestions. Thanks!

**Pull request merged**
