### PR TITLE
Feat/spotlightclick

### PR DESCRIPTION
**Pull request by davidseid**
@annisakaraca - Hi Annisa, not sure if you are planning to work more tonight or tomorrow, but here is another PR for you to look at if you get a second. If you aren't planning to work more this weekend no worries, it can wait til Monday. 

This PR mainly includes some changes to user interaction functionality in the gallery view, particularly the spotlight component and banner component. I also tried to make my tests stronger for my Gallery component by testing state changes based on user interaction. Lastly, I took my index.html and main.css out of .gitignore and did some minor refactoring in a few other spots. I didn't do a great job of concentrating this pull request on a single aspect, so hopefully it isn't too confusing. Thanks!

### CODE REVIEW

**Comment by davidseid** [comment]
[As a user, Show / Hide Working Photo List in Gallery View (Stretch goal)](https://trello.com/c/Fe9j37Uc/11-as-a-user-show-hide-working-photo-list-in-gallery-view-stretch-goal)

**Comment by davidseid** [comment]
[As a user, click on the spotlight image should shift slides + 1](https://trello.com/c/xMcdh2I2/82-as-a-user-click-on-the-spotlight-image-should-shift-slides-1)

**Comment by annisakaraca** [comment]
@davidseid Just finished looking over this, it looks really good to me! I just have a few suggestions.

- Consider renaming the plusSlides method in Gallery.js. When I first saw the name, I wasn't sure if it was the name of a function or a value, so perhaps consider something that sounds a little more like an action? It could also be a misnomer because its used to increment and decrement your slide index.
- Your tests look well written and clear, but I think you could go a little further with some of them. I think a big functionality of the Banner component execute the toggleGalleryView method when clicked, but I didn't see that being covered in the tests for that component, similarly to how you simulated a click in the Gallery tests. In the thumbnails component, I would also consider testing the conditional rendering, since you implemented that in this PR. 
- I'm not familiar on best practices for testing components and how atomic the tests should be, but I noticed the Spotlight component's new functionality was being tested in the Gallery test file, which makes sense because it updates the Gallery's state. I would consider doing further testing on the Spotlight component by itself as well, seeing as it is an important component.

Great work on this feature! It's awesome seeing all of your components come together.

- Annisa

**Comment by davidseid** [comment]
@annisakaraca - Thanks for the great feedback. I renamed the plusSlides and also changed currentSlide to makeCurrentSlide. I appreciate your suggestions on improving testing, my component testing is definitely not comprehensive as it is and I plan to add the tests you suggest next week and hopefully a bunch more.

**Pull request merged**
